name : CI-NodeJs
on:
    workflow_dispatch:
jobs:
    job1:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [16, 18]
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
            exclude:
                - node-version: 16
                  operating-system: ubuntu-latest
                - node-version: 16
                  operating-system: windows-latest
                - node-version: 16
                  operating-system: macos-latest
            include:
                - node-version: 22
                  operating-system: ubuntu-latest
                - node-version: 22
                  operating-system: windows-latest
                - node-version: 22
                  operating-system: macos-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
            - name: build the code
              run: npm run build
            - name: Deploy the code
              run: echo "Deploying the code..."
