name: CI-JAVA
on:
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    build-java-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
              with:
                repository: https://github.com/Skillfyme06-Nov-Org/SonarQubeCoverageJava.git
            - name: Set up JDK 17
              uses: actions/setup-java@v5
              with:
                java-version: '17'
                distribution: 'temurin'
            - name: Build the code
              run: mvn package 
